### PR TITLE
Icon and Icon.sys Improvements

### PR DESCRIPTION
**Pull request by NathanNeurotic**
This PR adds more detailed icon.sys lines, adds a "Do Not Delete" delete icon to the sets to discourage users from deleting important files in the browser.
BOOT icon was updated to include a mini-lock and mini-gears icons.
SYS-CONF icon was updated to include mini-lock and wrench icons.
FMCB icons were updated to have mini-lock and mini-gears icons.
image
image
Graphics created/modified by [BlackNinja](https://github.com/koraxial)

### CODE REVIEW

**Comment by kNOwAHitall** [comment]
FMCB-1 953  _ _FMCB-1 953_20240824130142
FMCB-1 953  _ _FMCB-1 953_20240824130139
FMCB-1 953  _ _FMCB-1 953_20240824130134
FMCB-1 953  _ _FMCB-1 953_20240824130130
FMCB-1 953  _ _FMCB-1 953_20240824130126
FMCB-1 953  _ _FMCB-1 953_20240824130121

**Comment by TnA-Plastic** [comment]
Nice work! @NathanNeurotic and BlackNinja!

**Comment by israpps** [comment]
It's nice but it will eat up more space...

not sure if all users will like that

**Comment by NathanNeurotic** [comment]
The per-install difference isn't much, while offering a uniform design and indicators for the users who delete/don't understand their setups.

We can adapt and tweak the results to fit your vision.
I'll see if we can optimize anything any further, maybe sway you.
image
image

**Comment by israpps** [comment]
I wish there was a way for icon.sys to reference another icon with absolute path
that way we could have
```
mc?;/SYS-CONF/DONTDELETEME.ICN
```
and reference it from all needed folders

@TnA-Plastic

**Pull request closed without merging**
